### ISSUE TITLE
Type size information.

### ISSUE THREAD

**Issue by rainwoodman** [arteymix/numeric-glib#3]
probably add the instance_size database here?

**Comment by arteymix** [comment]
I'll add a wrapper around g_boxed_type_register_static to store additional information.

We could add type info from built-in numerical types as well.

**Comment by rainwoodman** [comment]
Revive? Store in a local table, or does GLib provide a facility for this?

**Comment by arteymix** [comment]
There's been interesting development with binary-coded decimal recently.

It will be stored in a local table, GLib only support copying and freeing boxed types, and we cannot really extend the value types directly (gint32, guint32, etc.).

**Comment by arteymix** [comment]
Discussion can be pursued in #17
